id: P004642
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3165
  title: མདོ་སྡེའི་རྒྱན་གྱི་དགོངས་དོན་རྣམ་པར་བཤད་པ་ཐེག་མཆོག་བདུད་རྩིའི་དགའ་སྟོན
  author: ''
  volumes:
    527455f1424c46cb912f3f9cc18dad6a:
      image_group_id: I1KG3195
      title: ''
      volume_number: 1
      total_pages: 1316
